### ISSUE TITLE
incorrect data uploaded through github action

### ISSUE THREAD

**Issue by alvizek** [SRJPE/jpe-feather-edi#10]
- Kassie sent updated data on 1/23. This data file did not include discharge which was previously included. Inigo made decision to remove discharge and test internally. Inigo removed discharge from validated dataset and then tested process with the data Kassie provided. The GitHub action passed and data were uploaded to EDI (1239.4); however the data uploaded included the discharge column.
- This is strange for multiple reasons: the action should have failed because the metadata and data would not have matched unless existing data and not the new data were being used, the new data uploaded and called in the metadata script do not include discharge, the new data uploaded are only through March 2023 whereas Kassie provided data through Jan 2024.
- I created a new branch to test this and encountered some interesting behavior. I remove the turbidity column to test. (1) could not create xml because the metadata contained more fields than the data (this is what I would have expected to happen in the github action, (2) after updating the metadata to match the update on staging passed but it should not have and it wasn't actually posted. `✔ data package posted to EDI. Check EDI staging to confirm
[1] TRUE` The version number is off 1239.5 but on staging we are at 1239.18. (3) I updated the version to 1239.19 and when running update on staging it times out.

**Comment by alvizek** [comment]
Here are my notes/conclusions:
1. Did you upload the correct data to the blob? The trap file on the main branch in the repo doesn’t include discharge but stops at Mar 2023 instead of extending to Jan 2024.
2. The mystery about why the old data are being pushed - It looks like the xml is being created THEN the new data files are being pulled into the branch (based on looking at the Actions under `commit xml`)
3. This is what needs to happen:
    1. Checkout branch
    2. Add data files
    4. Merge into main
    5. Run make_metadata.xml script

Alternatively could update the url however this would be annoying and confusing to maintain because the main branch should be the link to the live url

**Comment by InigoP** [comment]
1. Found the bug that was causing it to upload already validated data. That's fixed now.
2. For the github action, the workflow that we previously decided upon was to:
- Checkout branch
- Add data files
- Run make_metadata.xml script
- Merge into main

We could rework over this workflow if needed.

**Comment by InigoP** [comment]
I also encountered the timeout issue when trying to work with the staging environment.
